language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: t4zWa89BoIBySYNx3Vi4th5NfyD9IJsizi6xWoqm3WR6HeIhiEhxYTYIdf9aBObTwC1MYJtrjy4pQRMCrCQEUSE1bZpHzALM0aNNvfUcivmyQk4qNw1yYyD2WkoxPvdlVQK//afyidglPcSRpX7+8Mwlmznv/UIqYXHIFVcb3xgl70eZz3eo7nNst1fbKDjdvU/MDJUPVx6U9VRTp5LMEnplYMaXzBgtQb6r8a71J9Xf8u41FyaG1WhR8lDC345f5ZSXtkqVXtW0cwGyYU0MkpkwGZRIg9HtqWFEg4P7bBoxBvv0QwV/JzugPXZHC4S8QJUxf/k2zd+Qh3D8CdTT2pyXqfvnb0Yw16yid+xiUq6rWNBgfxd1o8c0wkCS1fx230DNQAIDhxfl0b/vYWbm5VWPyujqrqENeSCQK03A0QxpPKQ9SWX2z3gQIMc3GxrpFDDSOoRIb/4Fxjg99E5eIRl7MSUWDnB4bE6c7dekY0KP+h+j70PVmLqZT2qYbZ9q237TZVTxAVYGccCbdrETR6rEjkCt4H+GOwSgQownjwzdqLK9cIfkLlcRxwujsruRDESF6u43fMvGHC0BtxxXTAMsQ3zJ5rq7pAd/wuyktohEG3VzeVnclV3J+wuYZ85YivAjxTgzCcOXMnUzmqDfpGX/R6BQEAGmaS2xuS7Hgho=
  on:
    repo: WingChhun/react-giftGiver
